version: '2'

volumes:
  postgres-data:

networks:
  divisas:

services:
  postgres:
    image: postgres:9
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: divisas
      POSTGRES_PASSWORD: divisas
    networks:
      - divisas
  tomcat:
    image: tomcat:8-jre8
    volumes:
      - ./docker-data/tomcat:/root/.boadivisas
      - ./ws/target/ws.war:/usr/local/tomcat/webapps/divisas.war
      - ./logs:/usr/local/tomcat/logs
    networks:
          - divisas
    ports:
      - "8077:8080"
      - "7776:7776"
    env_file:
      - ./tomcat.env